language: ruby
script: "bundle exec rake test_with_coveralls"
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
gemfile:
  - gemfiles/rails3.0.gemfile
  - gemfiles/rails3.1.gemfile
  - gemfiles/rails3.2.gemfile
  # - gemfiles/rails4.0.gemfile
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - jeremy.olliver@gmail.com
